name: Check air quality
on:
 schedule:
    - cron: '0 * * * *'
jobs:
  Run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Python script
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - run: |
          pip install -r requirements.txt
          python get_sensor_data.py
