name: Manage air quality
on:
 schedule:
    - cron: '*/5 * * * *'
jobs:
  Manage-air-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
          cache: 'pip'
      - name: Setup python requirements
        run: pip install -r requirements.txt
      - name: Run script
        run: python manage_air_quality.py --a 50 --f 15
        env:
          NEST_GCP_PROJECT_ID: ${{secrets.NEST_GCP_PROJECT_ID}}
          NEST_GCP_DEVICE_ID: ${{secrets.NEST_GCP_DEVICE_ID}}
          NEST_GCP_CLIENT_SECRET: ${{secrets.NEST_GCP_CLIENT_SECRET}}
          NEST_GCP_REFRESH_TOKEN: ${{secrets.NEST_GCP_REFRESH_TOKEN}}
          NEST_GCP_CLIENT_ID: ${{secrets.NEST_GCP_CLIENT_ID}}
          PURPLE_AIR_DEVICE_ID: ${{secrets.PURPLE_AIR_DEVICE_ID}}
          PURPLE_AIR_READ_API_KEY: ${{secrets.PURPLE_AIR_READ_API_KEY}}
