name: Manage air quality
on:
 push:
 schedule:
    - cron: '*/5 * * * *'
jobs:
  Manage-air-quality:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
          cache: 'pip'
      - name: Setup python requirements
        run: pip install -r requirements.txt
      - name: Run script
        run: python manage_air_quality.py --a 50 --f 60
        env:
          ECOBEE_API_KEY: ${{secrets.ECOBEE_API_KEY}}
          ECOBEE_AUTH_CODE: ${{secrets.ECOBEE_AUTH_CODE}}
          ECOBEE_REFRESH_TOKEN: ${{secrets.ECOBEE_REFRESH_TOKEN}}
          PURPLE_AIR_DEVICE_ID: ${{secrets.PURPLE_AIR_DEVICE_ID}}
          PURPLE_AIR_READ_API_KEY: ${{secrets.PURPLE_AIR_READ_API_KEY}}
