name: Manage air quality
on:
 schedule:
    - cron: '*/5 * * * *'
jobs:
  Manage-air-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run Python script
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.2'
      - run: |
          pip install -r requirements.txt
          python manage_air_quality.py
        env:
          NEST_GCP_PROJECT_ID: ${{secrets.NEST_GCP_PROJECT_ID}}
          NEST_GCP_DEVICE_ID: ${{secrets.NEST_GCP_DEVICE_ID}}
          NEST_GCP_CLIENT_SECRET: ${{secrets.NEST_GCP_CLIENT_SECRET}}
          NEST_GCP_REFRESH_TOKEN: ${{secrets.NEST_GCP_REFRESH_TOKEN}}
          NEST_GCP_CLIENT_ID: ${{secrets.NEST_GCP_CLIENT_ID}}
